auto: true
# Site settings
title: w66g
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://w66g.github.io
feed: /atom.xml


# Build settings
markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title/

